version: '3.8'
volumes:
  my-project_volumn:

networks:
  myproject-network:
    external:
      name: myproject-network

services:
  myproject-service:
    container_name:
      myproject-service
    build:
      context: .
    ports:
      - "5000:5000"
    networks:
      - myproject-network
#    depends_on:
#      - myproject-db
    restart: always
