version: '3.8'
volumes:
  my-project_volumn:

networks:
  myproject-network:
    external:
      name: myproject-network

services:
  myproject-service:
    container_name:
      myproject-service
    build:
      context: .
    ports:
      - "5000:5000"
    networks:
      - myproject-network
#    depends_on:
#      - myproject-db
    restart: always

#  quanlybanhang-db:
#    image:
#      mysql:8
#    container_name:
#      quanlybanhang-db-service
#    ports:
#      - "32001:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD: 123456
#      MYSQL_DATABASE: quanlybanhang
#      MYSQL_USER: soafinal
#      MYSQL_PASSWORD: 123456
#    networks:
#      - quanlysieuthi-network
#    volumes:
#      - quanlybanhang-volumn:/var/lib/mysql
